version: "3.7"

services:
  # App (アプリケーション)
  app:
    build:
      context: .
      target: develop
    volumes:
      - .:/go/src/github.com/grandcolline/layered-demo:cached
      # --- exclude volums ---
      - /go/src/github.com/grandcolline/layered-demo/.docker/
      - /go/src/github.com/grandcolline/layered-demo/.git/
    environment:
      # --- MongoDBの設定 ---
      MONGO_HOST: "mongo"
      MONGO_USER: "root"
      MONGO_PASSWORD: "root"
      MONGO_DATABASE: "app"
    ports:
      - 8080:8080
    depends_on:
      - mongo

  # MONGO（データベース）
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo/configdb:/data/configdb
